apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
   - password=root
resources: 
  - deploy mysql.yml
  - deploy wp.yml
  - efs-provisioner.yml
  - rbac.yml
  - storageclass.yml